    STRUCT('FB_HabiMarca_Awareness' AS cmp, 'Brand' AS grp),
    STRUCT('FB_HabiMarca_Awareness_Campaña_Navidad' AS cmp, 'Brand' AS grp),
    STRUCT('FB_HabiMarca_Awareness_Campaña_Navidad_interaccion' AS cmp, 'Brand' AS grp),
    STRUCT('FB_Habimetro_CDMX_Conversiones' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-fb-ds-cpa-habimetromx-intereses-v4-avaluo-gratis' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('tuh-mex-hmt-pai-per-web-mta-mld-mvi-nal-hbm' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_performance_max_habimetro' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_habimetro_cdmx' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_habimetro_cdmx' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_habimetro_cdmx_avaluo_online5-rsa' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-gg-sr-cpa-searchmx-habi3' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-gg-sr-cpa-searchmx-sectorinmobiliario3' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('FB_Habimetro_Conversiones_Ciudades_Advantage_Web' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('FB_Habimetro_Conversiones_CR' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-lfr-mta-mld-oto-cmx-89' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-lfr-mta-otr-oto-nal-cll' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('BAU - Continued Flow Alpha Test' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_Habi_Convertion_Leadads_Nacional_Testing_Triada_Ao' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiMarca_LeadAds_RTGT_ConvLeadAds_LeadAds_Brand' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_ADVANTAGE_ConvLeadAds' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_AudiencesTest' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_Audiencias_Prospecting' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_Instagram_DM' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_MAR' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_NOMAR' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_TestV3' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_TestV4' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Instagram' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Messenger_ADV' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Messenger_V2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Reels_FormV2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Reels_FormV3' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_RTGT_ConvLeadAds_Nacional_2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_RTGT_ConvLeadAds_TEST' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_RTGT_ConvLeadAds_Test_2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-lfr-mta-mld-oto-nal' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('Test - Continued Flow Alpha Test' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('Test - Continued Flow Alpha Test - RAW' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('test lead: dummy data for campaign name' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-lfr-mta-mld-oto-nal-form_full_funnel' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-lfr-tka-tlg-tad-nal-smrt' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('Tuhabi_TikTok_MX_Performance_LeadAds_AutoTargeting' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-lfr-tka-tlg-tad-nal-smrt-simple-form' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_GABI_TEST_4' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_GABI_TEST_5' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_CTC_V1' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_GABI_TEST' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_GABI_TEST_2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_GABI_TEST_3' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_GABI_TEST_6' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_MABI_Test' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_SmartData' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_SmartData_2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_SmartData_3' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_SmartData_New' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_SmartData_test' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_SmartData_Test_Sebas' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('SD 3' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_RTGT_ConvLeadAds' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_RTGT_ConvLeadAds2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('Okol landing Direct' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-lfr-mta-mld-oto-nal-avg' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('Tuhabi_TikTok_MX_Performance_LeadAds2' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_BAU_A' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Whatsapp_TEST_B' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_ADVANTAGE_ConvLeadAds - PRUEBA' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Monterrey_ConvLeadAds' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_Guadalajara_ConvLeadAds' AS cmp, 'Lead Forms Paid' AS grp),
    STRUCT('tuhabi_antevenio_mail' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_performance_max_nal_ao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_brand_general_cdmx' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_brand_general_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_brand_general_mty' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_gen_venta_cdmx Max_Val_Roas_V2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_Habi_Convertionweb_Nacional_Testing_Ao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_CDMX_Conversiones' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_CDMX_Advantage_Web Control-BAU' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_CDMX_Advantage_Web Test-CLO' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Shopping' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_BAU' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Contacto' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_LeadAds_EDM_CDMX_Conversion_LeadAds_TestV2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Nacional_Conversiones_05_2024' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-fb-ds-cpl-socialmx-form' AS cmp, 'WEB Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-tel-mta-otr-oto-nal-clt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-web-mta-mld-oto-gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_display_smart_campaign' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_performance_max_nal_ao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_performance_max_nal_ao_1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_performance_max_nal_ao_bbdd_form' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_cdmx' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_cdmx Roas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_cdmx+Roas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_Gdl GDL Brand  - Target ROAS' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_mty' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_brand_general_nal_roas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_compra_mty' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_do_performance_max_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_cdmx' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_cdmx Max Val Roas CDMX Compra MQL Evento' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_cdmx_broad_casa6' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_Gdl_casa1-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_mty' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_mty Max Val Roas MTY Compra' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_nal_roas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_compra_nal_roas Ranking_Url' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_real_estate_cdmx Max Val Roas CDMX Real Estate' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_cdmx' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_cdmx Max_Val_Roas_V2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_casa_rapido2-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_casa1-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_casa2-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_departamento1-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_departamento2-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_infonavit1-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_infonavit2-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_Gdl_inmueble2-etas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_mty Max Val Roas MTY Venta' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_nal_Max_Val_Roas_V2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_landing_hipoteca' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_performance_max_nal_ao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_performance_max_nal_max_conv' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_performance_max_nal_max_conv_2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_performance_max_nal_max_conv_2_1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_performance_max_nal_max_conv_price' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_youtube_nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_gen_compra_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_gen_compra_nal_roas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_gen_venta_Gdl' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi-sel-pai-per-web-gga-gld-gdg-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-web-gga-gld-gdg-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_cdmx_broad' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_do_sem_gen_venta_mty' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_brand_general_nal_roas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('bing_tuhabi_mx_do_sem_gen_venta_nal_Max_Val_Roas_V2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_Habi_Convertionweb_Nacional_Testing_Ao_Adgroup1_17dejunioal30dejunio' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web_CR' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_Habiweb_Nacional_Conversiones_Audiencias' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Nacional_Conversiones_V2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Nacional_Trafico_07_2024' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-cdmx-cdmx-wa-wa-cpl-customer-botbasicoincompleto' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-fb-ds-cpa-socialmx-lanzamientocompramosmx' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-fb-ds-cpa-socialmx-ventaneroscompramos' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-mm-mm-cpl-arkeero-mail' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-mx-cdmx-prg-na-cpl-taboola-native' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-mx-nal-tod-gg-prf-cpa-performancemax' AS cmp, 'WEB Paid' AS grp),
    STRUCT('pcom-entrypoint-banner' AS cmp, 'WEB Paid' AS grp),
    STRUCT('sem_Google_Landing_Avaluo' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Tuhabi_TikTok_MX_Performance_Conversion_Smart' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Tuhabi_TikTok_MX_Performance_Conversion_CPA' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Tuhabi_TikTok_MX_Performance_Conversion_CPA_Audiences_Lead_Obj' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_CR' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Vacante_Comercial_MX' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_CDMX_Advantage_Web Control-BAU old' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_CDMX_Advantage_Web Test-CLO old' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_Habiweb_Nacional_Conversiones_ConvLAL' AS cmp, 'WEB Paid' AS grp),
    STRUCT('tuh-mex-sel-pai-per-web-mta-mld-mst-nal-broker_avatar' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web_Zonas' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web_BAU' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web_TEST' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Lead_Registration' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_MTY_Advantage_Web' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_GDL_Advantage_Web' AS cmp, 'WEB Paid' AS grp),
    STRUCT('aw_tuhabi_mx_youtube_tv' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web_ROAS_TEST' AS cmp, 'WEB Paid' AS grp),
    STRUCT('FB_HabiWeb_Conversiones_Nacional_Advantage_Web_BAU_TEST' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Tuhabi_Chatgpt_Conversiones_MX_Nacional' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-clg-bga-otr-oto-nal-2' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-habimetrointeresesbog-gratis' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-cn-tod-fb-ds-cpa-habimetrocnd-cliccnd' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-clg-avg-mta-otr-oto-nalnew' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-clg-mta-mtr-oto-nal-rgt' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-web-mta-mld-oto-nal-' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-web-mta-mld-oto-nal-new' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-fb-ds-cpa-habimetronacional-QualifiedLead' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-habimetro-lookalike-valor' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-habimetrobog-interesesgratis' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-cm-org-habimetro-261221' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-bo-tod-gg-prf-cpa-performancemaxhabimetrov1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-gg-sr-cpa-habimetroaon' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-gg-sr-cpa-habimetroaon-competenciav5' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-md-tod-gg-ds-cpa-habimetrodiscovery-upper1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-md-tod-gg-ds-cpa-habimetrov2-rsa1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-md-tod-gg-sr-cpa-competenciav2' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-web-gga-gwg-gpm-bog-' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-web-gga-gwg-gpm-nal-' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-web-gga-gwg-gsr-bog-nbn' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-web-gga-gwg-gsr-nal-' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-bo-tod-gg-prf-cpa-performancemaxhabimetro' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-bo-tod-gg-prf-cpa-performancemaxhabimetrov2' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-gg-performance_max-cpa-habimetro' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-gg-prf-cpa-performancemaxhabimetrov1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-ds-cpa-habimetrov2-rsa1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-performancemaxhabimetrov1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-ca-tod-gg-ds-cpa-habimetrov2dsa1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-md-tod-gg-ds-cpa-habimetrov2' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-md-tod-gg-prf-cpa-performancemaxhabimetrofebrero' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-ca-ca-qr-vr-cpa-habimetro-emcali' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fr-ds-cpa-fincaraiz-Habimetro_email1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-mm-mm-cpa-propietarioswihom-' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-ox-ds-cpc-habimetro2-970x250' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('hab-col-' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-tk-ds-cpa-habimetro-rmkt' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-tk-ds-cpa-habimetro-suscribe' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-tk-ds-cpa-habimetro-conversion' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-md-md-qr-vr-cpa-habimetro-ascensores' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-bo-tod-gg-performance_max-cpa-habimetro' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-mg-na-cpa-nativohabimetro' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-gen-habimetro-aon-avaluo-catastral1' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-gg-sr-cpa-habimetronacional' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext5' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext8' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext9' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext4' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-ca-tod-gg-sr-cpa-brandcali' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-md-md-fb-ds-cpa-intereses-forma' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-md-md-fb-ds-cpa-laestrella-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-sch-fb-ds-cpa-intereses' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-prf-cpa-discoverynacional-upper1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-et-ds-cpa-tiempoenero-1000x1000' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fr-ds-cpl-fincaraiz-970x250-banner_pta_edificios_¿se_vende?' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gdi-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gpm-bog-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gpm-nal-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gpm-med-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-bar-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-bog-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-bog-cpt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-bog-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-cal-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-car-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-eje-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-nal-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-nal-cpt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-nal-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-bwc-gsr-vda-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-gwg-gdi-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-gwg-gpm-bog-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-bga-gwg-gpm-nal-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-web-bga-bwc-gdi-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-bkn-fb-ds-cpa-intereses-2-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-socialbog-interesestorre' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-bra-web-mta-maw-oto-nal-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-bra-web-mta-maw-oto-nal-tra' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-bog-lal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-bog-rgt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-med' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-med-new' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-avw' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-avw-cpa' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-avw-v2.0' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-awo' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-cvlal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-lal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-lal-25' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-lal-cr' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-lal-mq' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-lal-v2.0' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-med-test-ab2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-med-test-ab1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-rgt-new' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-otr-oto-nal-test-cr' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-rgt-v2.0' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-rmt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-super-segmento' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-tao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-trd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-userpersona' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-otr-oto-nal-asc' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-otr-oto-nal-asc Campaña' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-otr-oto-nal-gca' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellers-nacional-prueba_MQL' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellers-nacional-rmkt_MQL' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hb_co_se_na_fb_cv_ld_sg_ao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-ca-tod-fb-ds-awr-esperas-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Habi-venta-suba-gg-sr-aon-marca' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-bog-gg-sr-cpa-customaudience-habi2-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-performancemaxbogota' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-performancemaxbogota-2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-performancemaxbogota-v2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-brandgeneralv2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-ca-ca-gg-sr-cpa-cali-habi2-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gdi-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gpm-bog-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gpm-nal-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-bar-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-bog-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-bog-cpt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-bog-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-barranquilla' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-cali' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-cal-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-car-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-nal-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-nal-brand' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-nal-cpt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-nal-nbn' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-vda-bnd' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gvi-nal-exp' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-web-gga-gld-gdi-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-performance_max-cpa-bogota' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-brandbogota' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-sellersbogota' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sm-cpa-sellersnacional' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext10' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-ext3' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-sellersnacional' AS cmp, 'WEB Paid' AS grp),
    STRUCT('__CAMPAIGN_NAME__' AS cmp, 'WEB Paid' AS grp),
    STRUCT('test' AS cmp, 'WEB Paid' AS grp),
    STRUCT('Venta Marketing' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-tlg-oto-nal-2024' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-twc-oto-bog' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-twc-oto-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-twc-oto-nal-2024' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-twc-oto-nal-cap-2.0' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-twc-oto-nal-smart' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-tk-ds-cpa-sellers-registro' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-tk-ds-cpa-sellers-registro-lal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-rgt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-bra-web-mta-maw-mvi-nal-bcn' AS cmp, 'Brand' AS grp),
    STRUCT('hab-col-sel-pai-bra-web-mta-maw-mvi-nal-bcn - Interacción' AS cmp, 'Brand' AS grp),
    STRUCT('hab-col-sel-pai-bra-web-mta-maw-mvi-nal-bcn - Interacción - Copia' AS cmp, 'Brand' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-userpersona-v2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-winclap' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-tka-twc-oto-nal-smart-NO USAR' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsm-nal-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-vda-' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-hmt-pai-per-clg-avg-mta-otr-oto-nal' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-bog-nonbrand' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-fb-ds-cpa-habimetronacional-zapier' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-habimetro-intereses-probaste' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-ventanerosbog-contado' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-discoverybogota-middle4' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-brandgeneralv2bogota-geo-rsa1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-searchbogota-casa3' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellers-lal_MQL' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellers-nacional-prueba' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellersnacional' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-tk-ds-cpa-sellers-registro-lal-promoted' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-gga-gwg-gsr-bog-brand' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-bog-fb-ds-cpa-nacionalprueba2-laldinamico' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-bog-fb-ds-cpa-nacionalprueba2-remarketingdinamico' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-habimetro-intereses-2minutos' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-habimetro-lookalike-precio-video' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-fb-ds-cpa-ventanerosbog-compro' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-ds-cpa-habimetrov2avaluoonline-etas3' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-discoverybogota-middle1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-prf-cpa-performancemaxbogota-v3' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-brandgeneralv2habi-etas1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-br-tod-fb-ds-cpa-pr-bancos-gif' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-br-tod-gg-sr-cpa-brandbarranquilla' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-cn-tod-gg-sr-cpa-searchcundinamarca-apartamentos2' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-md-tod-gg-sr-cpa-brandvalledeaburra' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-habimetronacional-2minutos' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellersremarketing' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-mg-na-cpa-nativonacional' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hb_co_se_fb_cv_ld_sg_ao' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-hm-co-nal-tod-tk-ds-cpa-habimetro-lal' AS cmp, 'Estudio Inmueble Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-es-re-cpa-estrenarcontraportada' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-brandgeneralv2com-etas1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-bo-tod-gg-sr-cpa-competitorsbogota' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-cn-tod-gg-sr-cpa-searchcundinamarca-habi-1' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-fb-ds-cpa-sellers-nacional-rmkt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-gg-sr-cpa-competitorsnacional' AS cmp, 'WEB Paid' AS grp),
    STRUCT('habi-venta-co-nal-tod-tk-ds-cpa-sellers-registro-rmkt' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-test' AS cmp, 'WEB Paid' AS grp),
    STRUCT('hab-col-sel-pai-per-web-mta-mld-oto-nal-BAU' AS cmp, 'WEB Paid' AS grp)